import { addArticle, deleteArticle, updateArticle } from './blogActions';

export const BLOG_ACTIONS_TYPES = {
  GET_ARTICLES: 'GET_ARTICLES',
  ADD_ARTICLE: 'ADD_ARTICLE',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
  EDIT_ARTICLE: 'EDIT_ARTICLE',
  GET_SINGLE_ARTICLE: 'GET_SINGLE_ARTICLE',
};

export const AUTH_ACTIONS_TYPES = {
LOGIN_START: 'LOGIN_START',
LOGIN_SUCCESS: 'LOGIN_SUCCESS',
LOGIN_FAIL: 'LOGIN_FAIL',
LOGOUT: 'LOGOUT',
REGISTER_START: 'REGISTER_START',
REGISTER_SUCCESS: 'REGISTER_SUCCESS',
REGISTER_FAIL: 'REGISTER_FAIL',
SET_ERROR_EMPTY: 'SET_ERROR_EMPTY',
CHECK_AUTH: 'CHECK_AUTH',
CHECK_AUTH_START: 'CHECK_AUTH_START',
CHECK_AUTH_SUCCESS: 'CHECK_AUTH_SUCCESS',
CHECK_AUTH_FAIL: 'CHECK_AUTH_FAIL',
}

export { addArticle, deleteArticle, updateArticle };
