export const IndividualContraindicationsInitialValues = {
  cardiovascularDisease: {
    hypertensiveDisease: false,
    stroke: false,
    infarct: false,
    pacemakerPresence: false,
    phlebitisPhlebosisThrombosis: false,
    comment: '',
  },
  gastrointestinalTractDiseases: {
    liverDisease: false,
    gallbladderDisease: false,
    comment: '',
  },
  endocrinology: {
    thyroidDisease: false,
    diabetes: false,
    comment: '',
  },
  otherConditions: {
    herpes: false,
    OX: false,
    hepatitis: false,
    tuberculosis: false,
    syphilis: false,
    epilepsy: false,
    oncology: false,
    kidneyDisease: false,
    edemaPredisposition: false,
    bruisingPredisposition: false,
    asthma: false,
    birthControlPills: false,
    neoplasm: false,
    demodicosis: false,
    exacerbationOfChronicDiseases: false,
    increaseBodyTemperature: false,
    psoriasis: false,
    pregnancyAndLactation: false,
    beautyInjections: false,
    metalImplants: false,
    comment: '',
  },
  lastMedication: '',
  stateAfter: {
    operations: false,
    laserGrinding: false,
    deepPeels: false,
    comment: '',
  },
  comment: '',
};
