export const ContactInformationInitialValues = {
  firstName: '',
  lastName: '',
  fatherName: '',
  birthdate: '',
  phone: '',
  email: '',
  instagram: '',
  facebook: '',
  tags: [''],
  skinType: {
    dry: false,
    normal: false,
    fat: false,
    combined: false,
    comment: '',
  },
  skinCondition: {
    problematic: false,
    sensitive: false,
    dehydrated: false,
    dryIrritated: false,
    fat: false,
    thin: false,
    rosacea: false,
    acne: false,
    pigmentation: false,
    fluffOnFace: false,
    hirsutism: false,
    bacterialViralSkinDiseases: false,
    comment: '',
  },
  allergicReactions: {
    food: false,
    medicines: false,
    cosmetics: false,
    comment: '',
  },
  morphotype: {
    tired: false,
    finelyWrinkled: false,
    edematousDeforming: false,
    mixed: false,
    muscular: false,
    comment: '',
  },
  comment: '',
};
